-- require("mason-nvim-dap").setup({
--     ensure_installed = {'python'},
--     handlers = {
--         function(config)
--           -- all sources with no handler get passed here
--
--           -- Keep original functionality
--           require('mason-nvim-dap').default_setup(config)
--         end,
--         python = function(config)
--             config.adapters = {
-- 	            type = "executable",
-- 	            command = "/usr/bin/python3",
-- 	            args = {
-- 		            "-m",
-- 		            "debugpy.adapter",
-- 	            },
--             }
--             require('mason-nvim-dap').default_setup(config) -- don't forget this!
--         end,
--     },
-- })
require("dapui").setup()
-- require('dap-go').setup({
--   on_attach = function()
--   end
-- })
--
-- local venv_path = "/usr/bin/python"
-- if os.getenv("VIRTUAL_ENV") then
--   venv_path = os.getenv("VIRTUAL_ENV") .. "/bin/python"
-- end
-- require('dap-python').setup()
-- require("nvim-dap-virtual-text").setup()

-- require("dapui").setup({
--   icons = { expanded = "▾", collapsed = "▸" },
--   mappings = {
--     -- Use a table to apply multiple mappings
--     expand = { "<CR>", "<2-LeftMouse>" },
--     open = "o",
--     remove = "d",
--     edit = "e",
--     repl = "r",
--     toggle = "t",
--   },
--   layouts = {
--     {
--       elements = {
--         'scopes',
--         'breakpoints',
--         'stacks',
--         'watches',
--       },
--       size = 40,
--       position = 'left',
--     },
--     {
--       elements = {
--         'repl',
--         'console',
--       },
--       size = 10,
--       position = 'bottom',
--     },
--   },
--   floating = {
--     max_height = nil, -- These can be integers or a float between 0 and 1.
--     max_width = nil, -- Floats will be treated as percentage of your screen.
--     border = "single", -- Border style. Can be "single", "double" or "rounded"
--     mappings = {
--       close = { "q", "<Esc>" },
--     },
--   },
--   windows = { indent = 1 },
-- })
